import Phaser from 'phaser';
import { Core } from '../core/Core';
import { RunSystem } from '../core/RunSystem';
type Gate=Phaser.GameObjects.Container&{lane?:number;gold?:boolean};
const COLORS=[0x22c55e,0x3b82f6,0xf43f5e],NAMES=['GREEN','BLUE','RED'],GOLD=0xfacc15;
export class ColorLane extends Phaser.Scene{
 lane=1;speed=220;playing=false;paused=false;spawnDelay=1180;run=new RunSystem();pattern:number[]=[];patternIndex=0;
 player!:Phaser.GameObjects.Rectangle;gates!:Phaser.GameObjects.Group;scoreText!:Phaser.GameObjects.Text;streakText!:Phaser.GameObjects.Text;livesText!:Phaser.GameObjects.Text;levelText!:Phaser.GameObjects.Text;
 title!:Phaser.GameObjects.Text;hint!:Phaser.GameObjects.Text;playText!:Phaser.GameObjects.Text;status!:Phaser.GameObjects.Text;pauseButton!:Phaser.GameObjects.Text;
 lanes=[65,195,325];constructor(){super('ColorLane');}
 create(){
  this.add.rectangle(195,422,390,844,0x0b1220);this.lanes.forEach((x,i)=>{this.add.rectangle(x,430,126,720,COLORS[i],.065);this.add.rectangle(x,430,2,720,0xffffff,.1);this.add.text(x,92,NAMES[i],{fontFamily:'Arial',fontSize:'13px',color:'#cbd5e1',fontStyle:'bold'}).setOrigin(.5);});
  this.add.text(18,18,'GECO GAMES',{fontFamily:'Arial',fontSize:'14px',color:'#94a3b8',fontStyle:'bold'});this.scoreText=this.add.text(370,14,'0',{fontFamily:'Arial',fontSize:'31px',color:'#fff',fontStyle:'bold'}).setOrigin(1,0);this.livesText=this.add.text(18,52,'♥ ♥ ♥',{fontFamily:'Arial',fontSize:'18px',color:'#fff'});this.levelText=this.add.text(195,52,'LEVEL 1',{fontFamily:'Arial',fontSize:'14px',color:'#94a3b8',fontStyle:'bold'}).setOrigin(.5);this.streakText=this.add.text(370,53,'',{fontFamily:'Arial',fontSize:'13px',color:'#fde047',fontStyle:'bold'}).setOrigin(1,0);
  this.pauseButton=this.add.text(195,805,'Ⅱ  PAUSE',{fontFamily:'Arial',fontSize:'15px',color:'#cbd5e1',fontStyle:'bold'}).setOrigin(.5).setDepth(30).setInteractive();this.pauseButton.on('pointerdown',(p:Phaser.Input.Pointer)=>{p.event.stopPropagation();if(this.playing)this.togglePause();});this.status=this.add.text(195,155,'',{fontFamily:'Arial',fontSize:'23px',color:'#fff',fontStyle:'bold'}).setOrigin(.5).setDepth(20);this.player=this.add.rectangle(this.lanes[1],720,64,64,COLORS[1]).setStrokeStyle(4,0xffffff,.95).setDepth(10);this.gates=this.add.group();
  this.title=this.add.text(195,275,'COLOR\nLANE',{align:'center',fontFamily:'Arial',fontSize:'52px',color:'#fff',fontStyle:'bold'}).setOrigin(.5);this.hint=this.add.text(195,435,'CATCH COLORS IN THEIR LANES\n\nPatterns get harder each level.\nGold blocks can be caught in ANY lane\nand award +5 coins.\n\n3 lives • streak bonuses • levels\nBEST '+Core.data.highScore,{align:'center',fontFamily:'Arial',fontSize:'17px',color:'#cbd5e1',lineSpacing:9}).setOrigin(.5);this.playText=this.add.text(195,635,'TAP TO PLAY',{fontFamily:'Arial',fontSize:'24px',color:'#fde047',fontStyle:'bold'}).setOrigin(.5);this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>{if(!this.playing){this.start();return;}if(this.paused)return;const x=p.x*(390/this.scale.displaySize.width);this.move(Math.max(0,Math.min(2,Math.floor(x/130))));});
 }
 move(i:number){if(i===this.lane)return;this.lane=i;this.player.setFillStyle(COLORS[i]);this.tweens.killTweensOf(this.player);this.tweens.add({targets:this.player,x:this.lanes[i],duration:95,ease:'Cubic.out'});if(Core.data.vibration&&navigator.vibrate)navigator.vibrate(7);}
 start(){this.time.removeAllEvents();this.gates.clear(true,true);this.run.reset();this.playing=true;this.paused=false;this.pattern=[];this.patternIndex=0;this.lane=1;this.player.setPosition(this.lanes[1],720).setFillStyle(COLORS[1]);this.scoreText.setText('0');this.updateHud();this.title.setVisible(false);this.hint.setVisible(false);this.playText.setVisible(false);this.flash('READY!',600);Core.event('run_start');this.time.delayedCall(500,()=>{this.spawn();this.scheduleSpawn();});}
 updateHud(){const s=this.run.snapshot();this.livesText.setText(Array(s.lives).fill('♥').join(' ')||'NO LIVES');this.levelText.setText('LEVEL '+s.level);this.streakText.setText(s.streak>=2?'STREAK '+s.streak+'/5':'');this.scoreText.setText(String(s.score));}
 scheduleSpawn(){if(!this.playing)return;this.time.delayedCall(this.spawnDelay,()=>{if(!this.playing)return;if(!this.paused)this.spawn();this.scheduleSpawn();});}
 chooseLane(){const lvl=this.run.level;if(this.patternIndex>=this.pattern.length){if(lvl<3)this.pattern=[Phaser.Math.Between(0,2)];else if(lvl<6){const a=Phaser.Math.Between(0,2),b=(a+Phaser.Math.Between(1,2))%3;this.pattern=[a,b,a];}else{const start=Phaser.Math.Between(0,2);this.pattern=Phaser.Math.Between(0,1)?[start,(start+1)%3,(start+2)%3]:[start,(start+2)%3,(start+1)%3,(start+2)%3];}this.patternIndex=0;}return this.pattern[this.patternIndex++];}
 spawn(){const gold=this.run.score>=5&&Phaser.Math.Between(1,12)===1;const lane=gold?Phaser.Math.Between(0,2):this.chooseLane();const color=gold?GOLD:COLORS[lane];const box=this.add.rectangle(this.lanes[lane],-38,gold?58:94,gold?58:48,color).setStrokeStyle(4,0xffffff,.95);const label=this.add.text(this.lanes[lane],-38,gold?'★ GOLD':NAMES[lane],{fontFamily:'Arial',fontSize:'13px',color:gold?'#111827':'#fff',fontStyle:'bold'}).setOrigin(.5);const g=this.add.container(0,0,[box,label]) as Gate;g.lane=lane;g.gold=gold;this.gates.add(g);}
 update(_:number,delta:number){if(!this.playing||this.paused)return;const lvl=this.run.level;this.speed=Math.min(610,220+(lvl-1)*42+this.run.score*2);this.spawnDelay=Math.max(540,1180-(lvl-1)*85);for(const obj of [...this.gates.getChildren()] as Gate[]){obj.y+=this.speed*delta/1000;if(obj.y>675&&!obj.getData('checked')){obj.setData('checked',true);if(obj.gold)this.goldCatch(obj);else if(obj.lane===this.lane)this.success(obj);else this.miss(obj);}if(obj.y>880)obj.destroy();}}
 success(obj:Gate){const x=this.lanes[obj.lane!];obj.destroy();const r=this.run.catch();this.burst(x,COLORS[this.lane]);this.flash(r.bonus?'STREAK BONUS +5 COINS!':'MATCH! +1',r.bonus?500:250);if(r.levelUp)this.time.delayedCall(300,()=>this.flash('LEVEL '+this.run.level+' • NEW PATTERNS!',650));this.tweens.add({targets:this.player,scale:1.24,yoyo:true,duration:80});if(Core.data.vibration&&navigator.vibrate)navigator.vibrate(15);this.updateHud();}
 goldCatch(obj:Gate){const x=this.lanes[obj.lane!];obj.destroy();this.run.score++;this.run.coins+=5;this.run.level=Math.floor(this.run.score/10)+1;this.burst(x,GOLD);this.flash('GOLD! +5 COINS',520);if(Core.data.vibration&&navigator.vibrate)navigator.vibrate([15,20,15]);this.updateHud();}
 burst(x:number,color:number){for(let i=0;i<8;i++){const d=this.add.circle(x,700,Phaser.Math.Between(3,7),color).setDepth(15);this.tweens.add({targets:d,x:x+Phaser.Math.Between(-70,70),y:700+Phaser.Math.Between(-80,35),alpha:0,scale:0,duration:320,onComplete:()=>d.destroy()});}}
 miss(obj:Gate){obj.destroy();const dead=this.run.miss();this.cameras.main.shake(150,.012);this.flash(dead?'LAST LIFE LOST!':'MISS! '+this.run.lives+' LIVES LEFT',500);if(Core.data.vibration&&navigator.vibrate)navigator.vibrate([45,25,70]);this.updateHud();if(dead){this.playing=false;this.time.delayedCall(420,()=>this.over());}}
 togglePause(){this.paused=!this.paused;this.pauseButton.setText(this.paused?'▶  RESUME':'Ⅱ  PAUSE');this.status.setText(this.paused?'PAUSED':'').setAlpha(1).setScale(1);if(!this.paused)this.status.setAlpha(0);Core.event(this.paused?'pause':'resume');}
 flash(t:string,d:number){this.status.setText(t).setAlpha(1).setScale(.82);this.tweens.add({targets:this.status,alpha:0,scale:1.1,duration:d});}
 over(){this.playing=false;this.paused=false;this.time.removeAllEvents();this.gates.clear(true,true);const s=this.run.snapshot();Core.finish(s.score,s.coins);Core.event('run_end',s);this.title.setText('RUN COMPLETE').setVisible(true);this.hint.setText('SCORE  '+s.score+'\nBEST  '+Math.max(Core.data.highScore,s.score)+'\nLEVEL  '+s.level+'\n\nCOINS EARNED  +'+s.coins+'\nTOTAL COINS  '+Core.data.coins).setVisible(true);this.playText.setText('TAP TO PLAY AGAIN').setVisible(true);this.pauseButton.setText('Ⅱ  PAUSE');this.status.setText('').setAlpha(0);}
}